### ISSUE TITLE
bug(commands): incorrect error messages

### ISSUE THREAD

**Issue by jontmy** [AY2223S1-CS2103T-W10-4/tp#199]
Tracking issue to merge the following issues:

**Issues with input arguments with whitespace but missing quotes:**

- [ ] #167 - `add mod`, also check `edit mod`
- [ ] #171 - `edit task`
- [ ] #192 - `edit task`

**Issues with invalid flags in input:**

- [ ] #174 - `add mod`, also check every command

**Issues with missing flags in message:**

- [ ] #177 - `-p` in `add task`, also check `edit task`
